---
services:
  hefes-analytics:
    image: ghcr.io/ryderhiew/hefes-analytics:latest
    build: .
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://hefes:hefes@hefes-db:5432/hefes_analytics
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      hefes-db:
        condition: service_healthy
    networks:
      - hefes-network
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  hefes-db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hefes_analytics
      POSTGRES_USER: hefes
      POSTGRES_PASSWORD: hefes
    volumes:
      - hefes-db-data:/var/lib/postgresql/data
    networks:
      - hefes-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  hefes-network:
    driver: bridge

volumes:
  hefes-db-data:
